import {Section} from "../../../field.model";

export const paracliniqueFields: Section[] = [
    {
        groupName: "GLOBULES",
        template: [
            {
                name: "gbmm3_label",
                label: "Globule Blancs (/mm3)",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'gbmm3',
                type: "input",
                col: 4,
                show: true,
            },
            {
                name: "gbmm3_with",
                label: "avec",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'gbmm3_space',
                type: "space",
                col: 2,
                show: true,
            },
            {
                name: "gbmm3pn",
                label: "% de Polynucleaires neutrophiles",
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "gbmm3l",
                label: "% de lymphocytes",
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "gbmm3de",
                label: "% d'eosinophiles",
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "gbmm3mo",
                label: "% de monocytes",
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "gbmm3ba",
                label: "% de basophiles",
                type: "input",
                col: 2,
                show: true,
            },
            {
                type: 'line',
                col: 12,
                show: true,
            },
            {
                name: "hemogdl",
                label: "Hémoglobine (g/dl)",
                type: "input",
                col: 4,
                show: true,
            },
            {
                name: "grmm3",
                label: "Globules rouges (/mm3)",
                type: "input",
                col: 4,
                show: true,
            },
            {
                name: "plaqmm3",
                label: "Plaquettes (/mm3)",
                type: "input",
                col: 4,
                show: true,
            },
            {
                type: 'line',
                col: 12,
                show: true,
            },
            {
                name: "vs_l",
                label: "La VS est ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'vs_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "al1h_l",
                label: "a la 1ere heure  ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'al1h_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "al1mm_l",
                label: "mm",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "crp_l",
                label: "La CRP est ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'crp_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "crpa_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'crpmg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "crpmg_l",
                label: "mg/l",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "ge_l",
                label: "La GE est ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'ge_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "gea_l",
                label: "densité parasitaire ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'gemg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "gemg_l",
                label: "/µl",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "glyc_l",
                label: "La glycemie est ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'glyc_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "glyca_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'glycmg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "glycmg_l",
                label: "mg/dl",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "uree_l",
                label: "L'urée est ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'uree_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "ureea_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'ureemg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "ureemg_l",
                label: "mg/dl",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "creat_l",
                label: "La créatinine est ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'creat_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "creata_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'creatmg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "creatmg_l",
                label: "mg/dl",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "sgot_l",
                label: "SGOT ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'sgot_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "sgota_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'sgotmg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "sgotmg_l",
                label: "Ul/l",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "sgpt_l",
                label: "SGPT ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'sgpt_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "sgpta_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'sgptmg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "sgptmg_l",
                label: "Ul/l",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "gamma_l",
                label: "Gamma GT ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'gamma_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "gammaa_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'gammamg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "gammamg_l",
                label: "Ul/l",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "tp_l",
                label: "TP ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'tp_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "tpa_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'tpmg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "tpmg_l",
                label: "%",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: "tck_l",
                label: "TCK ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'tck_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "tcka_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'tckmg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "tckmg_l",
                label: "sec",
                type: "label",
                col: 2,
                show: true,
            },

            {
                name: "tsk_l",
                label: "TS ",
                type: "label",
                col: 2,
                show: true,
            },
            {
                name: 'tsk_v',
                type: "input",
                col: 3,
                show: true,
            },
            {
                name: "tska_l",
                label: "a ",
                type: "label",
                col: 3,
                show: true,
            },
            {
                name: 'tskmg_v',
                type: "input",
                col: 2,
                show: true,
            },
            {
                name: "tskmg_l",
                label: "sec",
                type: "label",
                col: 2,
                show: true,
            },
        ],
        resume: ""
    },
    {
        groupName: "BIOCHIMIE DU SANG",
        template: [

        ],
        resume: 'wwww 555 '
    }
]